// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokRichtext, StoryblokMultilink, StoryblokAsset } from '../storyblok.d.ts';
export interface StoryblokAge {
  component: "age";
  _uid: string;
}

export interface StoryblokButton {
  component: "button";
  _uid: string;
}

export interface StoryblokEducation {
  school: string;
  start_date: string;
  end_date: string;
  component: "education";
  _uid: string;
}

export interface StoryblokExperience {
  company_name: string;
  position: string;
  start_date: string;
  end_date?: string;
  description?: StoryblokRichtext;
  tags?: ("Startup" | "Volunteer" | "Freelance")[];
  component: "experience";
  _uid: string;
}

export interface StoryblokGrid {
  columns?: (
    | StoryblokAge
    | StoryblokButton
    | StoryblokEducation
    | StoryblokExperience
    | StoryblokGrid
    | StoryblokLanguage
    | StoryblokMedia
    | StoryblokPage
    | StoryblokProject
    | StoryblokResume
    | StoryblokSiteConfig
    | StoryblokSkills
  )[];
  component: "grid";
  _uid: string;
}

export interface StoryblokLanguage {
  name: string;
  level: "Native" | "Professional" | "Fluent";
  component: "language";
  _uid: string;
}

export interface StoryblokMedia {
  component: "media";
  _uid: string;
}

export interface StoryblokPage {
  body?: (StoryblokGrid | StoryblokMedia | StoryblokResume)[];
  type: "website" | "article";
  meta_title?: string;
  meta_description?: string;
  component: "page";
  _uid: string;
}

export interface StoryblokProject {
  name: string;
  description: StoryblokRichtext;
  tech_stack?: StoryblokSkills[];
  github_url?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  live_url?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  is_featured?: boolean;
  open_source?: boolean;
  image?: StoryblokAsset;
  component: "project";
  _uid: string;
}

export interface StoryblokResume {
  experience?: (ISbStoryData<StoryblokExperience> | string)[];
  projects?: (ISbStoryData<StoryblokProject> | string)[];
  education?: (ISbStoryData<StoryblokEducation> | string)[];
  skills?: (ISbStoryData<StoryblokSkills> | string)[];
  languages?: StoryblokLanguage[];
  component: "resume";
  _uid: string;
}

export interface StoryblokSiteConfig {
  site_name: string;
  email?: string;
  location?: string;
  title?: string;
  summary?: StoryblokRichtext;
  github?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  linkedin?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  logo?: StoryblokAsset;
  download_cv_text?: string;
  cv_file?: StoryblokAsset;
  header_navigation?: (
    | StoryblokAge
    | StoryblokButton
    | StoryblokEducation
    | StoryblokExperience
    | StoryblokGrid
    | StoryblokLanguage
    | StoryblokMedia
    | StoryblokPage
    | StoryblokProject
    | StoryblokResume
    | StoryblokSiteConfig
    | StoryblokSkills
  )[];
  footer_navigation?: (
    | StoryblokAge
    | StoryblokButton
    | StoryblokEducation
    | StoryblokExperience
    | StoryblokGrid
    | StoryblokLanguage
    | StoryblokMedia
    | StoryblokPage
    | StoryblokProject
    | StoryblokResume
    | StoryblokSiteConfig
    | StoryblokSkills
  )[];
  cookie_consent_text?: StoryblokRichtext;
  cookie_consent_prompt_text?: StoryblokRichtext;
  cookie_consent_accept_label?: string;
  cookie_consent_decline_label?: string;
  hide_blocks_that_require_cookie_consent?: boolean;
  component: "site-config";
  _uid: string;
}

export interface StoryblokSkills {
  frontend?: ("React" | "Next.js" | "Vue" | "JavaScript" | "TypeScript" | "TailwindCSS")[];
  backend?: ("Node.js" | "C# (.NET)" | "Java" | "NestJS" | "MongoDB" | "PostgreSQL" | "GraphQL" | "Redis")[];
  tools?: ("Git" | "Docker" | "Kubernetes" | "Linux" | "Nginx" | "AWS" | "Azure")[];
  component: "skills";
  _uid: string;
}

export type ContentType =
  | StoryblokEducation
  | StoryblokExperience
  | StoryblokPage
  | StoryblokProject
  | StoryblokSiteConfig
  | StoryblokSkills;
