name: Deploy

on:
  release:
    types: [published]

env:
  NODE_VERSION: "20"
  SPOTIFY_OAUTH_CLIENT_ID: ${{ secrets.SPOTIFY_OAUTH_CLIENT_ID }}
  SPOTIFY_OAUTH_SECRET: ${{ secrets.SPOTIFY_OAUTH_SECRET }}
  SPOTIFY_OAUTH_REDIRECT_URI: ${{ secrets.SPOTIFY_OAUTH_REDIRECT_URI }}
  SPOTIFY_OAUTH_REFRESH_TOKEN: ${{ secrets.SPOTIFY_OAUTH_REFRESH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup NodeJS Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm install --force

      - name: Build Application
        run: npm run build

      - name: Archive Production Artifacts
        run: tar -czvf app.tar.gz .next public src/env *.cjs *.mjs *.ts *.json

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: app

      - name: Copy Artifacts to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "./app.tar.gz"
          target: "~/maxwiggedal.dev"

      - name: Deploy To VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
            sed -i 's/^SPOTIFY_OAUTH_CLIENT_ID=.*/SPOTIFY_OAUTH_CLIENT_ID=${{ secrets.SPOTIFY_OAUTH_CLIENT_ID }}/' ~/maxwiggedal.dev/.env || echo "SPOTIFY_OAUTH_CLIENT_ID=${{ secrets.SPOTIFY_OAUTH_CLIENT_ID }}" >> ~/maxwiggedal.dev/.env
            sed -i 's/^SPOTIFY_OAUTH_SECRET=.*/SPOTIFY_OAUTH_SECRET=${{ secrets.SPOTIFY_OAUTH_SECRET }}/' ~/maxwiggedal.dev/.env || echo "SPOTIFY_OAUTH_SECRET=${{ secrets.SPOTIFY_OAUTH_SECRET }}" >> ~/maxwiggedal.dev/.env
            sed -i 's/^SPOTIFY_OAUTH_REDIRECT_URI=.*/SPOTIFY_OAUTH_REDIRECT_URI=${{ secrets.SPOTIFY_OAUTH_REDIRECT_URI }}/' ~/maxwiggedal.dev/.env || echo "SPOTIFY_OAUTH_REDIRECT_URI=${{ secrets.SPOTIFY_OAUTH_REDIRECT_URI }}" >> ~/maxwiggedal.dev/.env
            sed -i 's/^SPOTIFY_OAUTH_REFRESH_TOKEN=.*/SPOTIFY_OAUTH_REFRESH_TOKEN=${{ secrets.SPOTIFY_OAUTH_REFRESH_TOKEN }}/' ~/maxwiggedal.dev/.env || echo "SPOTIFY_OAUTH_REFRESH_TOKEN=${{ secrets.SPOTIFY_OAUTH_REFRESH_TOKEN }}" >> ~/maxwiggedal.dev/.env
            tar -xzvf ~/maxwiggedal.dev/app.tar.gz -C ~/maxwiggedal.dev
            cd ~/maxwiggedal.dev
            npm install
            pm2 restart ecosystem.config.cjs
