name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup NodeJS Environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Archive Production Artifacts
        run: tar -czvf app.tar.gz .next public *.js *.ts *.json

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: app

      - name: Copy Artifacts to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "./app.tar.gz"
          target: "~/maxwiggedal.dev"

      - name: Deploy To VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
            echo "export PORT=${{ secrets.PORT }}" >> ~/.bashrc
            echo "export SPOTIFY_OAUTH_CLIENT_ID=${{ secrets.SPOTIFY_OAUTH_CLIENT_ID }}" >> ~/.bashrc
            echo "export SPOTIFY_OAUTH_SECRET=${{ secrets.SPOTIFY_OAUTH_SECRET }}" >> ~/.bashrc
            echo "export SPOTIFY_OAUTH_REDIRECT_URI=${{ secrets.SPOTIFY_OAUTH_REDIRECT_URI }}" >> ~/.bashrc
            echo "export SPOTIFY_OAUTH_REFRESH_TOKEN=${{ secrets.SPOTIFY_OAUTH_REFRESH_TOKEN }}" >> ~/.bashrc
            echo "export NEXT_PUBLIC_GA_TRACKING_ID=${{ secrets.NEXT_PUBLIC_GA_TRACKING_ID }}" >> ~/.bashrc
            source ~/.bashrc
            tar -xzvf ~/maxwiggedal.dev/app.tar.gz -C ~/maxwiggedal.dev
            cd ~/maxwiggedal.dev
            npm install
            pm2 restart ecosystem.config.js
